name: Test Unity

on: 
  workflow_call:

jobs:
  testAllModes:
    name: Test all modes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ManualDi.Sync.Unity3d
          - ManualDi.Async.Unity3d

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup common packages
        run: |
          sh setup.sh
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          artifactsPath: artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results ${{ matrix.projectPath }}
          path: artifacts
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results ${{ matrix.projectPath }}
          path: ${{ steps.tests.outputs.coveragePath }}